coverage:
  precision: 2
  round: down
  range: 70...100
  status:
    project: true
    patch: true
    changes: false
  ignore:
    - "libcdata/*"
    - "libcerror/*"
    - "libcfile/*"
    - "libclocale/*"
    - "libcnotify/*"
    - "libcthreads/*"
    - "libfcrypto/*"
    - "libfdatetime/*"
    - "libfguid/*"
    - "libfmos/*"
    - "libfplist/*"
    - "libfvalue/*"
    - "libfwevt/*"
    - "libfwnt/*"
    - "libhmac/*"
    - "libuna/*"
    - "tests/*"
