= WMI repository file formats

:toc:
:toclevels: 4

:numbered!:
[abstract]
== Summary
The WMI repository, also known as the Common Information Model (CIM) repository,
holds the schema, also called the object repository or class store, that models
the managed environment and defines every piece of data exposed by WMI.

This document is intended as a working document for the WMI repository file
format specifications. Which should allow existing Open Source forensic
tooling to be able to process these file types.

[preface]
== Document information
[cols="1,5"]
|===
| Author(s): | Joachim Metz <joachim.metz@gmail.com>
| Abstract: | This document contains information about the WMI repository file formats
| Classification: | Public
| Keywords: | OBJECTS.DATA, WMI repository
|===

[preface]
== License
....
Copyright (C) 2015-2016, Joachim Metz <joachim.metz@gmail.com>.
Permission is granted to copy, distribute and/or modify this document under the 
terms of the GNU Free Documentation License, Version 1.3 or any later version 
published by the Free Software Foundation; with no Invariant Sections, no 
Front-Cover Texts, and no Back-Cover Texts. A copy of the license is included 
in the section entitled "GNU Free Documentation License".
....

[preface]
== Revision history
[cols="1,1,1,5",options="header"]
|===
| Version | Author | Date | Comments
| 0.0.1 | J.B. Metz | May 2015 | Initial version.
| 0.0.2 | J.B. Metz | November 2015 | Additional information about index binary-tree file format.
| 0.0.3 | J.B. Metz | November 2015 | Additional information about objects.data file format.
| 0.0.4 | J.B. Metz | February 2016 | Additional information.
|===

:numbered:
== Overview
The WMI repository, also known as the Common Information Model (CIM) repository,
holds the schema, also called the object repository or class store, that models
the managed environment and defines every piece of data exposed by WMI.

The location and format of the WMI repository varies per Windows version.

=== Windows 9x/Me, NT 4 and 2000
In Windows 95 OSR 2.5, Windows 98, Windows Millennium Edition (Me) the CIM 
repository can be found in the directory:
....
%WinDir%\System\Wbem\Repository\cim.rep
....

[yellow-background]*Determine format*

In Windows NT 4.0 with SP4 and Windows 2000 the CIM repository can be found in 
the directory:
....
%SystemRoot%\System32\Wbem\Respository\
....

* `CIM.REC`;
* `CIM.REP`;

[yellow-background]*Determine format*

=== Windows XP and later
In Windows XP and Windows 2003 the CIM repository can be found in the directory:
....
%SystemRoot%\System32\WBEM\Repository\FS
....

In Windows Vista and later the CIM repository can be found in the directory:
....
%SystemRoot%\System32\WBEM\Repository\
....

[yellow-background]*TODO: determine if SysWOW64 is used as well.*
....
%SystemRoot%\SysWOW64\WBEM\Repository\
....

* `Index.btr`; index binary-tree file;
* `Index.map`; index mappings file;
* `Objects.data`; objects data file;
* `Objects.map`; objects mappings file;
* `Mapping#.map`; mappings file where # is:
** `[1-2]` in Windows XP and Windows 2003
** `[1-3]` in Windows Vista and later
* `Mapping.ver`; mappings version file contains # of the active mappings file.

[NOTE]
A copy of the CIM repository is stored in the system restore points.

=== Test version
Files created by the following version of programs were used to test the 
information within this document:

* [yellow-background]*Windows 95*
* [yellow-background]*Windows 98*
* [yellow-background]*Windows Me*
* [yellow-background]*Windows NT4*
* Windows 2000
* Windows XP
* Windows 2003
* [yellow-background]*Windows Vista*
* Windows 2008
* Windows 7
* [yellow-background]*Windows 2012*
* Windows 8
* Windows 10

== The index binary-tree file (index.btr)
The index binary-tree file (index.btr) consists of:

* an array of pages

=== Index binary-tree page
The index binary-tree page is 8192 bytes of size and consists of:

* a page header
* [yellow-background]*Unknown*
* sub pages
* page key offsets
* page key data
* page value offsets
* page value data
* padding (0-byte values)

=== Index binary-tree page header
The index binary-tree page header is 20 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | Index page type +
See section: <<index_binary_tree_page_types,Index binary-tree page types>>
| 4 | 4 | | Mapped page number +
The page number is mapped to the in-file page number via the index mappings file
| 8 | 4 | | [yellow-background]*Unknown (empty values)*
| 12 | 4 | | Mapped root page number +
[yellow-background]*Only set in the administrative page and 0 otherwise?* +
The page number is mapped to the in-file page number via the index mappings file
| 16 | 4 | | Number of keys
|===

=== [[index_binary_tree_page_types]]Index binary-tree page types

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x0000 | | [yellow-background]*Unknown*
| 0xaccc | | [yellow-background]*Unknown (Is active)*
| 0xaddd | | [yellow-background]*Unknown (Is administrative)*
| 0xbadd | | [yellow-background]*Unknown (Is deleted)*
|===

=== Index binary-tree page unknown array
The index binary-tree page unknown array is variable of size and consists of:

* number of keys x [yellow-background]*Unknown array entry*

The unknown entry is 4 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | [yellow-background]*Unknown (empty values)*
|===

=== Index binary-tree page sub pages
The index binary-tree page sub pages are variable of size and consists of:

* (number of keys + 1) x sub page number

The unknown entry is 4 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | Mapped sub page number +
The page number is mapped to the in-file page number via the index mappings file
|===

=== Index binary-tree page key offsets
The index binary-tree page key offsets are variable of size and consist of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | ... | | array of 16-bit offsets +
The offsets are relative to the start of the index binary-tree page key data
|===

[NOTE]
The number of offsets equals the number of keys.

=== Index binary-tree page key data
The index binary-tree page key data is variable of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 2 | | The number of page key segment indexes
| 2 | ... | | Array 16-bit page key segment indexes
|===

The page key segment indexes refer to page values where a page key consists of
multiple page values e.g.
....
VALUE1 / VALUE2 / VALUE3
....

=== Index binary-tree page value offsets
The index binary-tree page value offsets are variable of size and consist of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 2 | | number of offsets
| 2 | ... | | array of 16-bit offsets +
The offsets are relative to the start of the index binary-tree page value data
|===

=== Index binary-tree page value data
The index binary-tree page value data is variable of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 2 | | data size +
Contains the number of bytes of the data
| 2 | ... | | data
|===

== Index.map, Mapping#.map and Objects.map

[yellow-background]*TODO: maps x to Objects.data page numbers*

The mapping file consists of:

* file header
* mappings
* unknown entries
* file footer

=== Notes
The contents of the `Mapping#.map` file appears to be a concattenation of
the contents of the `Objects.map` and `Index.map` files. The file header
data differs.

[yellow-background]*TODO: what is the role of the invidual files and the
concattenated files?*

=== File header
The file header is 8 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | 0x0000abcd | [yellow-background]*Unknown (signature)*
| 4 | 4 | | [yellow-background]*Unknown (format version and flags?)*
|===

....
0x000035be => Mapping#.map
0x000035bf => Index.map, Objects.map
....

[yellow-background]*TODO: check Windows 7 file header*

=== Mappings
The mappings are variable of size and consis of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | number of entries
| 4 | ... | | array of entries
|===

=== Mapping entry - Windows XP
The mapping entry - Windows XP is 24 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | [yellow-background]*Unknown (page number)*
|===

[yellow-background]*TODO: what about MSB in the page number*
[yellow-background]*TODO: 0xffffffff unavailable*

=== Mapping entry - Windows 7
[yellow-background]*TODO: check?*

The mapping entry - Windows 7 is 24 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | [yellow-background]*Unknown (page number)*
| 4 | 4 | | [yellow-background]*Unknown (checksum)* +
[yellow-background]*Contains a CRC-32?*
| 8 | 4 | | [yellow-background]*Unknown (free space?)*
| 12 | 4 | | [yellow-background]*Unknown (used space?)*
| 16 | 4 | | [yellow-background]*Unknown (identifier?)*
| 20 | 4 | | [yellow-background]*Unknown (identifier?)*
|===

[yellow-background]*TODO: what about MSB ini page number*

=== Unknown entries
[yellow-background]*TODO: are these free pages?*

The unknown entries are variable of size and consis of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | number of entries
| 4 | ... | | array of entries
|===

[yellow-background]*TODO: 32-bit entry contains page size?*

=== File footer

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | 0x0000dcba | [yellow-background]*Unknown*
|===

== Mapping.ver
The `Mapping.ver` file is used in Windows XP and Windows 2003 to indicate the
active `Mapping#.map` file.

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | The active mapping file.
|===

== Objects.data
The Objects.data file consists of:

* an array of pages

=== Objects data page
The objects data page is 8192 bytes of size and consists of:

* Object descriptors
* [yellow-background]*unknown records*
* [yellow-background]*unknown*

[cols="1,5",options="header"]
|===
| Characteristics | Description
| Byte order | little-endian
| Date and time values | FILETIME in UTC
| Character strings | ASCII strings are Single Byte Character (SBC) or Multi Byte Character (MBC) string stored with a codepage. Sometimes referred to as ANSI string representation. +
Though technically maybe incorrect, this document will use term (extended) ASCII string. +
Unicode strings are stored in UTF-16 little-endian without the byte order mark (BOM).
|===

==== Object descriptors
The object descriptors consists of:

* an array of object descriptor entries
* empty (zero byte filled) object descriptor (or terminator)

===== Object descriptor entry
The object descriptor entry is 16 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | Object identifier
| 4 | 4 | | Object record data offset +
The offset is relative to the start of the object descriptors
| 8 | 4 | | Object record data size
| 12 | 4 | | Object record data checksum +
Contains a CRC-32 with polynomial 0xedb88320 and initial value 0 of the object record data
|===

==== Object record
The object record is variable of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | [yellow-background]*Unknown string size* +
Contains the number of characters
| 4 | ... | | [yellow-background]*Unknown string* +
UTF-16 little-endian string without end-of-string character.
| ... | 8 | | [yellow-background]*Unknown data and time* +
Contains a FILETIME +
4+| _Unknown data_
| ... | 2 | | [yellow-background]*Unknown size* +
The size of the unknown data that includes the size of size value +
[yellow-background]*Assumed to be 16-bit*
| ... | 7 | 0x00 | [yellow-background]*Unknown (empty values?)*
4+| _Unknown value_
| ... | 4 | | [yellow-background]*Unknown (value type?)*
| ... | 4 | | [yellow-background]*Unknown (value size?)*
| ... | 1 | 0x00 | [yellow-background]*Unknown (string flags?)*
| ... | ... | | [yellow-background]*Unknown (value string?)* +
ASCII string terminated by an end-of-string character
4+| _Unknown data_
| ... | 2 | | [yellow-background]*Unknown (data size?)*
| ... | ... | | [yellow-background]*Unknown data*
4+| _Unknown_
| ... | 2 | | [yellow-background]*Unknown (string data size?)*
| ... | 2 | 0x8000 | [yellow-background]*Unknown*
4+| _String data_
| ... | 1 | 0x00 | [yellow-background]*Unknown (string flags?)*
| ... | ... | | [yellow-background]*Unknown (string?)* +
ASCII string terminated by an end-of-string character
4+| _Unknown data_
| ... | 2 | 0x000c | [yellow-background]*Unknown size* +
The size of the unknown data that includes the size of size value +
[yellow-background]*Assumed to be 16-bit*
| ... | 9 | 0x00 | [yellow-background]*Unknown (empty values?)*
| ... | 1 | 0x80 | [yellow-background]*Unknown (sentinal?)*
|===

....
00000210                                             67 00  |e.n.t.^]4.....g.|
00000220  00 00 00 00 00 00 00 11  00 00 00 23 00 00 00 00  |...........#....|
00000230  5f 5f 4e 61 6d 65 73 70  61 63 65 4f 70 65 72 61  |__NamespaceOpera|
00000240  74 69 6f 6e 45 76 65 6e  74 00                    |tionEvent.......|

00000240                                 1b 00              |tionEvent.......|
00000240                                       00 00 04 00  |tionEvent.......|
00000250  00 00 00 00 00 00 3f ff  ff ff ff ff ff ff ff ff  |......?.........|
00000260  ff ff ff ff ff ff ff                              |............__Na|

00000260                       1a  00 00 80                 |............__Na|

00000260                                    00 5f 5f 4e 61  |............__Na|
00000270  6d 65 73 70 61 63 65 43  72 65 61 74 69 6f 6e 45  |mespaceCreationE|
00000280  76 65 6e 74 00                                    |vent............|

00000280                 0c 00 00  00 00 00 00 00 00 00 00  |vent............|
00000290  80                                                |.               |
....

....
Another record type? or is the record header omitted?
0x00000000  37 00 31 00 31 00 34 00  30 00 43 00 43 00 44 00  7.1.1.4.0.C.C.D.
0x00000010  36 00 36 00 45 00 44 00  43 00 32 00 30 00 42 00  6.6.E.D.C.2.0.B.
0x00000020  39 00 43 00 32 00 43 00  44 00 46 00 35 00 32 00  9.C.2.C.D.F.5.2.
0x00000030  46 00 33 00 43 00 38 00  33 00 37 00 33 00 41 00  F.3.C.8.3.7.3.A.
0x00000040  43 00 41 00 39 00 46 00  39 00 36 00 36 00 44 00  C.A.9.F.9.6.6.D.
0x00000050  38 00 30 00 41 00 34 00  33 00 41 00 44 00 36 00  8.0.A.4.3.A.D.6.
0x00000060  39 00 38 00 41 00 35 00  42 00 46 00 43 00 44 00  9.8.A.5.B.F.C.D.
0x00000070  46 00 35 00 31 00 35 00  34 00 39 00 44 00 44 00  F.5.1.5.4.9.D.D.
0x00000080  fb 86 91 4f 27 04 ca 01  a3 86 91 4f 27 04 ca 01  ...O'......O'...
0x00000090  66 00 00 00 00 00 00 00  00 00 1e 00 00 00 04 00  f...............
0x000000a0  00 00 01 4f 00 00 80 00  5f 5f 4d 65 74 68 6f 64  ...O....__Method
0x000000b0  50 72 6f 76 69 64 65 72  52 65 67 69 73 74 72 61  ProviderRegistra
0x000000c0  74 69 6f 6e 00 00 5c 5c  2e 5c 52 6f 6f 74 5c 43  tion..\\.\Root\C
0x000000d0  49 4d 56 32 3a 5f 5f 57  69 6e 33 32 50 72 6f 76  IMV2:__Win32Prov
0x000000e0  69 64 65 72 2e 4e 61 6d  65 3d 22 43 69 6d 77 69  ider.Name="Cimwi
0x000000f0  6e 33 32 41 22 00                                 n32A".
....

==== [yellow-background]*Unknown*

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
|===

....
*
00002000  00 00 00 00 00 00 00 00  00 00 00 0c 00 00 00 00  |................|
00002010  00 5f 5f 00 00 00 80 00  43 6f 6d 70 72 65 73 73  |.__.....Compress|
00002020  00 29 00 00 00 10 12 00  00 00 0b 00 00 00 ff ff  |.)..............|
00002030  1d 12 00 00 01 08 00 00  00 25 12 00 00 2c 12 00  |.........%...,..|
00002040  00 02 08 20 00 00 36 12  00 00 00 49 6d 70 6c 65  |... ..6....Imple|
00002050  6d 65 6e 74 65 64 00 00  53 63 68 65 6d 61 00 00  |mented..Schema..|
00002060  57 69 6e 33 32 00 00 56  61 6c 75 65 4d 61 70 00  |Win32..ValueMap.|
00002070  0d 00 00 00 6e 12 00 00  71 12 00 00 74 12 00 00  |....n...q...t...|
00002080  77 12 00 00 7a 12 00 00  7e 12 00 00 82 12 00 00  |w...z...~.......|
00002090  86 12 00 00 8a 12 00 00  8e 12 00 00 92 12 00 00  |................|
000020a0  96 12 00 00 9a 12 00 00  00 30 00 00 32 00 00 38  |.........0..2..8|
000020b0  00 00 39 00 00 31 30 00  00 31 31 00 00 31 32 00  |..9..10..11..12.|
000020c0  00 31 33 00 00 31 34 00  00 31 35 00 00 31 36 00  |.13..14..15..16.|
000020d0  00 31 37 00 00 32 31 00  00 00 00 00 6e 01 00 00  |.17..21.....n...|
000020e0  05 00 54 45 53 54 00 00  52 4f 4f 54 5c 43 49 4d  |..TEST..ROOT\CIM|
000020f0  56 32 00 1d 00 00 00 00  ff ff ff ff 00 00 00 00  |V2..............|
00002100  04 00 00 00 04 00 00 00  00 00 00 00 00 00 00 80  |................|
00002110  0c 00 00 00 00 00 00 00  00 00 00 80 26 01 00 00  |............&...|
00002120  00 00 00 00 00 05 00 00  00 04 00 00 00 0f 00 00  |................|
00002130  00 0e 00 00 00 00 0b 00  00 00 ff ff 01 00 00 00  |................|
00002140  2a 00 00 00 6b 00 00 00  19 ff ff ff ff 95 00 00  |*...k...........|
00002150  80 00 5f 5f 50 41 52 41  4d 45 54 45 52 53 00 00  |..__PARAMETERS..|
00002160  61 62 73 74 72 61 63 74  00 13 00 00 00 00 00 00  |abstract........|
00002170  00 00 00 00 00 00 00 04  00 00 00 00 52 65 74 75  |............Retu|
00002180  72 6e 56 61 6c 75 65 00  00 75 69 6e 74 33 32 00  |rnValue..uint32.|
00002190  13 00 00 00 00 00 00 00  00 00 00 00 00 00 11 00  |................|
000021a0  00 00 0a 00 00 80 03 08  00 00 00 5e 00 00 00 00  |...........^....|
000021b0  75 69 6e 74 33 32 00 00  6f 75 74 00 13 00 00 00  |uint32..out.....|
000021c0  00 00 00 00 00 00 00 00  00 00 1c 00 00 00 0a 00  |................|
000021d0  00 80 03 08 00 00 00 5e  00 00 00 66 00 00 00 00  |.......^...f....|
000021e0  0b 00 00 00 ff ff 00 0c  00 00 00 00 00 5f 5f 00  |.............__.|
000021f0  00 00 80 43 3a 00 00 00  00 00 00 00 00 00 00 00  |...C:...........|
00002200  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
....

....
Empty?
*
00003100  00 00 00 00 00 00 00 00  0c 00 00 00 00 00 5f 5f  |..............__|
00003110  0c 00 00 00 00 00 5f 5f  00 00 00 80 00 00 00 00  |......__........|
00003120  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
....

....
*
00003df0  00 0c 00 00 00 00 00 5f  5f 0c 00 00 00 00 00 5f  |.......__......_|
00003e00  5f 00 00 00 80 00 00 00  00 00 00 00 00 00 00 00  |_...............|
00003e10  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00003e20  00 00 00 00 00 00 00 00  00 00 00 00 00 0c 00 00  |................|
00003e30  00 00 00 5f 5f 00 00 00  80 4f 57 53 00 00 00 00  |...__....OWS....|
00003e40  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
....

....
00004160  09 00 00 c6 09 00 00 de  09 00 00 a3 0a 00 00 b8  |................|
00004170  0a 00 00 7a 0b 00 00 95  0b 00 00                 |...z............|

Bitmap?
00004170                                    ff ff ff ff 7f  |...z............|
00004180  55 55 57 d5 ff ff ff ff  ff ff ff ff ff ff ff ff  |UUW.............|
00004190  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
*
00004200  ff ff ff ff                                       |....]....CIM_Vol|

Unknown
00004200              5d 0c 00 80  00 43 49 4d 5f 56 6f 6c  |....]....CIM_Vol|
00004210  74 61 67 65 53 65 6e 73  6f 72 00 00 4c 6f 63 61  |tageSensor..Loca|
00004220  6c 65 00 00 55 55 49 44  00 00 7b 41 39 39 38 46  |le..UUID..{A998F|
00004230  39 42 34 2d 45 33 44 34  2d 31 31 64 32 2d 38 36  |9B4-E3D4-11d2-86|
00004240  30 31 2d 30 30 30 30 46  38 31 30 32 45 35 46 7d  |01-0000F8102E5F}|
00004250  00 00 41 62 73 74 72 61  63 74 00 00 41 63 63 75  |..Abstract..Accu|
00004260  72 61 63 79 00 03 40 00  00 1b 00 62 00 00 00 04  |racy..@....b....|
00004270  00 00 00 36 00 00 00 0a  00 00 80 03 08 00 00 00  |...6............|
00004280  a1 00 00 00 03 00 00 80  02 0b 00 00 00 ff ff a9  |................|
00004290  00 00 00 00 08 00 00 00  b3 00 00 00 bd 00 00 00  |................|
000042a0  02 08 20 00 00 cd 00 00  00 00 73 69 6e 74 33 32  |.. .......sint32|
000042b0  00 00 4f 76 65 72 72 69  64 65 00 00 41 63 63 75  |..Override..Accu|
....

....
00006190  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
*
000061f0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff bb     |................|

String:
000061f0                                                0c  |................|
00006200  00 80 00 43 49 4d 5f 55  6e 69 6e 74 65 72 72 75  |...CIM_Uninterru|
00006210  70 74 69 62 6c 65 50 6f  77 65 72 53 75 70 70 6c  |ptiblePowerSuppl|
00006220  79 00 00 44 65 73 63 72  69 70 74 69 6f 6e 00 00  |y..Description..|
....

....
String table header?

0093bff0                                       00 00 00 00  |................|
0093c000  01 00 00 00 5f 03 00 00  ff 01 00 00              |...._...........|

String table entry?
* index
* size
* checksum/hash?
* unknown?
0093c000                                       01 00 00 00  |...._...........|
0093c010  0d 00 00 00 cf 74 84 50  00 00 00 00              |.....t.P........|

0093c010                                       02 00 00 00  |.....t.P........|
0093c020  4c 00 00 00 96 5d d8 98  00 00 00 00 05 00 00 00  |L....]..........|
...
0093c2f0  03 00 00 00 69 37 33 fa  00 00 00 00 41 00 00 00  |....i73.....A...|
0093c300  33 00 00 00 a5 0c ef 93  00 00 00 00 42 00 00 00  |3...........B...|
...
0093e9e0  7e 00 00 00 0c 58 ba ac  00 00 00 00 73 04 00 00  |~....X......s...|
0093e9f0  da 19 00 00 19 ee 9d b2  00 00 00 00              |............CD_3|

0093e9f0                                       43 44 5f 33  |............CD_3|
0093ea00  43 41 41 45 30 37 44 30  36 42 36 31 33 43 45 38  |CAAE07D06B613CE8|
0093ea10  39 41 39 44 33 31 44 31  36 46 38 33 42 39 35 2e  |9A9D31D16F83B95.|
0093ea20  33 31 34 2e 39 30 32 39  35 39 2e 38 34 37 00     |314.902959.847.C|

0093ea20                                                43  |314.902959.847.C|
0093ea30  44 5f 34 36 43 41 36 42  34 45 41 36 41 46 46 45  |D_46CA6B4EA6AFFE|
0093ea40  46 39 34 30 38 42 32 45  37 35 42 37 44 38 42 39  |F9408B2E75B7D8B9|
....

== CIM repository
=== Notes
Mapped index page 0 references the administrative page in the index binary-tree

The root page number of the administrative page in the index binary-tree

=== Index binary-tree identifier strings
The page values in the index binary-tree (Index.btr) contain identifier strings
that map to object records. Example of identifier strings are:

....
R_7F02F51F97C31228F1ADE773040492C4
R_889E073E24E009B2E955B1E9560E641E.625.860151.342
....

The values in the identifier string can contain segments seperated by '.'

[cols="1,5",options="header"]
|===
| Segment index | Usage
| 0 | Type prefix and MD5 hash
2+| _Optional values_
| 1 | Objects data mappings index number
| 2 | Object identifier
| 3 | Object record data size
|===

The following the prefixes are known:

[cols="1,5",options="header"]
|===
| Prefix | Usage
| CD | Class definition
| CI | 
| CR | 
| I | 
| KI | 
| KL | 
| NS | Name space
| R | 
|===

=== Class definition (CD)

[yellow-background]*TODO: add descriptions*

== Notes

Listing name spaces:
....
gwmi -namespace "root" -class "__Namespace" | Select Name
....

Listing classes:
....
gwmi -namespace root\cimv2 -list
....

:numbered!:
[appendix]
== References

`[DMTF]`

[cols="1,5",options="header"]
|===
| Title: | CIM Schema: Version 2.45.0
| URL: | http://www.dmtf.org/standards/cim/cim_schema_v2450
|===

`[FLAREWMI]`

[cols="1,5",options="header"]
|===
| Title: | Flare WMI project
| URL: | https://github.com/fireeye/flare-wmi
|===

`[MSDN]`

[cols="1,5",options="header"]
|===
| Title: | `[MS-WMIO]`: CimType
| URL: | https://msdn.microsoft.com/en-us/library/cc250928.aspx
|===

`[TECHNET]`

[cols="1,5",options="header"]
|===
| Title: | Technet: WMI Infrastructure
| URL: | https://technet.microsoft.com/en-us/library/ee198935.aspx
|===

`[TUNSTALL02]`

[cols="1,5",options="header"]
|===
| Title: | Developing WMI Solutions: A Guide to Windows Management Instrumentation
| Author(s): | Craig Tunstall, Gwyn Cole
| Date: | November 22, 2002
|===

[appendix]
== GNU Free Documentation License
Version 1.3, 3 November 2008
Copyright © 2000, 2001, 2002, 2007, 2008 Free Software Foundation, Inc. 
<http://fsf.org/>

Everyone is permitted to copy and distribute verbatim copies of this license 
document, but changing it is not allowed.

=== 0. PREAMBLE
The purpose of this License is to make a manual, textbook, or other functional 
and useful document "free" in the sense of freedom: to assure everyone the 
effective freedom to copy and redistribute it, with or without modifying it, 
either commercially or noncommercially. Secondarily, this License preserves for 
the author and publisher a way to get credit for their work, while not being 
considered responsible for modifications made by others.

This License is a kind of "copyleft", which means that derivative works of the 
document must themselves be free in the same sense. It complements the GNU 
General Public License, which is a copyleft license designed for free software.

We have designed this License in order to use it for manuals for free software, 
because free software needs free documentation: a free program should come with 
manuals providing the same freedoms that the software does. But this License is 
not limited to software manuals; it can be used for any textual work, 
regardless of subject matter or whether it is published as a printed book. We 
recommend this License principally for works whose purpose is instruction or 
reference.

=== 1. APPLICABILITY AND DEFINITIONS
This License applies to any manual or other work, in any medium, that contains 
a notice placed by the copyright holder saying it can be distributed under the 
terms of this License. Such a notice grants a world-wide, royalty-free license, 
unlimited in duration, to use that work under the conditions stated herein. The 
"Document", below, refers to any such manual or work. Any member of the public 
is a licensee, and is addressed as "you". You accept the license if you copy, 
modify or distribute the work in a way requiring permission under copyright law.

A "Modified Version" of the Document means any work containing the Document or 
a portion of it, either copied verbatim, or with modifications and/or 
translated into another language.

A "Secondary Section" is a named appendix or a front-matter section of the 
Document that deals exclusively with the relationship of the publishers or 
authors of the Document to the Document's overall subject (or to related 
matters) and contains nothing that could fall directly within that overall 
subject. (Thus, if the Document is in part a textbook of mathematics, a 
Secondary Section may not explain any mathematics.) The relationship could be a 
matter of historical connection with the subject or with related matters, or of 
legal, commercial, philosophical, ethical or political position regarding them.

The "Invariant Sections" are certain Secondary Sections whose titles are 
designated, as being those of Invariant Sections, in the notice that says that 
the Document is released under this License. If a section does not fit the 
above definition of Secondary then it is not allowed to be designated as 
Invariant. The Document may contain zero Invariant Sections. If the Document 
does not identify any Invariant Sections then there are none.

The "Cover Texts" are certain short passages of text that are listed, as 
Front-Cover Texts or Back-Cover Texts, in the notice that says that the 
Document is released under this License. A Front-Cover Text may be at most 5 
words, and a Back-Cover Text may be at most 25 words.

A "Transparent" copy of the Document means a machine-readable copy, represented 
in a format whose specification is available to the general public, that is 
suitable for revising the document straightforwardly with generic text editors 
or (for images composed of pixels) generic paint programs or (for drawings) 
some widely available drawing editor, and that is suitable for input to text 
formatters or for automatic translation to a variety of formats suitable for 
input to text formatters. A copy made in an otherwise Transparent file format 
whose markup, or absence of markup, has been arranged to thwart or discourage 
subsequent modification by readers is not Transparent. An image format is not 
Transparent if used for any substantial amount of text. A copy that is not 
"Transparent" is called "Opaque".

Examples of suitable formats for Transparent copies include plain ASCII without 
markup, Texinfo input format, LaTeX input format, SGML or XML using a publicly 
available DTD, and standard-conforming simple HTML, PostScript or PDF designed 
for human modification. Examples of transparent image formats include PNG, XCF 
and JPG. Opaque formats include proprietary formats that can be read and edited 
only by proprietary word processors, SGML or XML for which the DTD and/or 
processing tools are not generally available, and the machine-generated HTML, 
PostScript or PDF produced by some word processors for output purposes only.

The "Title Page" means, for a printed book, the title page itself, plus such 
following pages as are needed to hold, legibly, the material this License 
requires to appear in the title page. For works in formats which do not have 
any title page as such, "Title Page" means the text near the most prominent 
appearance of the work's title, preceding the beginning of the body of the text.

The "publisher" means any person or entity that distributes copies of the 
Document to the public.

A section "Entitled XYZ" means a named subunit of the Document whose title 
either is precisely XYZ or contains XYZ in parentheses following text that 
translates XYZ in another language. (Here XYZ stands for a specific section 
name mentioned below, such as "Acknowledgements", "Dedications", 
"Endorsements", or "History".) To "Preserve the Title" of such a section when 
you modify the Document means that it remains a section "Entitled XYZ" 
according to this definition.

The Document may include Warranty Disclaimers next to the notice which states 
that this License applies to the Document. These Warranty Disclaimers are 
considered to be included by reference in this License, but only as regards 
disclaiming warranties: any other implication that these Warranty Disclaimers 
may have is void and has no effect on the meaning of this License.

=== 2. VERBATIM COPYING
You may copy and distribute the Document in any medium, either commercially or 
noncommercially, provided that this License, the copyright notices, and the 
license notice saying this License applies to the Document are reproduced in 
all copies, and that you add no other conditions whatsoever to those of this 
License. You may not use technical measures to obstruct or control the reading 
or further copying of the copies you make or distribute. However, you may 
accept compensation in exchange for copies. If you distribute a large enough 
number of copies you must also follow the conditions in section 3.

You may also lend copies, under the same conditions stated above, and you may 
publicly display copies.

=== 3. COPYING IN QUANTITY
If you publish printed copies (or copies in media that commonly have printed 
covers) of the Document, numbering more than 100, and the Document's license 
notice requires Cover Texts, you must enclose the copies in covers that carry, 
clearly and legibly, all these Cover Texts: Front-Cover Texts on the front 
cover, and Back-Cover Texts on the back cover. Both covers must also clearly 
and legibly identify you as the publisher of these copies. The front cover must 
present the full title with all words of the title equally prominent and 
visible. You may add other material on the covers in addition. Copying with 
changes limited to the covers, as long as they preserve the title of the 
Document and satisfy these conditions, can be treated as verbatim copying in 
other respects.

If the required texts for either cover are too voluminous to fit legibly, you 
should put the first ones listed (as many as fit reasonably) on the actual 
cover, and continue the rest onto adjacent pages.

If you publish or distribute Opaque copies of the Document numbering more than 
100, you must either include a machine-readable Transparent copy along with 
each Opaque copy, or state in or with each Opaque copy a computer-network 
location from which the general network-using public has access to download 
using public-standard network protocols a complete Transparent copy of the 
Document, free of added material. If you use the latter option, you must take 
reasonably prudent steps, when you begin distribution of Opaque copies in 
quantity, to ensure that this Transparent copy will remain thus accessible at 
the stated location until at least one year after the last time you distribute 
an Opaque copy (directly or through your agents or retailers) of that edition 
to the public.

It is requested, but not required, that you contact the authors of the Document 
well before redistributing any large number of copies, to give them a chance to 
provide you with an updated version of the Document.

=== 4. MODIFICATIONS
You may copy and distribute a Modified Version of the Document under the 
conditions of sections 2 and 3 above, provided that you release the Modified 
Version under precisely this License, with the Modified Version filling the 
role of the Document, thus licensing distribution and modification of the 
Modified Version to whoever possesses a copy of it. In addition, you must do 
these things in the Modified Version:

A. Use in the Title Page (and on the covers, if any) a title distinct from that 
of the Document, and from those of previous versions (which should, if there 
were any, be listed in the History section of the Document). You may use the 
same title as a previous version if the original publisher of that version 
gives permission. 

B. List on the Title Page, as authors, one or more persons or entities 
responsible for authorship of the modifications in the Modified Version, 
together with at least five of the principal authors of the Document (all of 
its principal authors, if it has fewer than five), unless they release you from 
this requirement. 

C. State on the Title page the name of the publisher of the Modified Version, 
as the publisher. 

D. Preserve all the copyright notices of the Document. 

E. Add an appropriate copyright notice for your modifications adjacent to the 
other copyright notices. 

F. Include, immediately after the copyright notices, a license notice giving 
the public permission to use the Modified Version under the terms of this 
License, in the form shown in the Addendum below. 

G. Preserve in that license notice the full lists of Invariant Sections and 
required Cover Texts given in the Document's license notice. 

H. Include an unaltered copy of this License. 

I. Preserve the section Entitled "History", Preserve its Title, and add to it 
an item stating at least the title, year, new authors, and publisher of the 
Modified Version as given on the Title Page. If there is no section Entitled 
"History" in the Document, create one stating the title, year, authors, and 
publisher of the Document as given on its Title Page, then add an item 
describing the Modified Version as stated in the previous sentence. 

J. Preserve the network location, if any, given in the Document for public 
access to a Transparent copy of the Document, and likewise the network 
locations given in the Document for previous versions it was based on. These 
may be placed in the "History" section. You may omit a network location for a 
work that was published at least four years before the Document itself, or if 
the original publisher of the version it refers to gives permission. 

K. For any section Entitled "Acknowledgements" or "Dedications", Preserve the 
Title of the section, and preserve in the section all the substance and tone of 
each of the contributor acknowledgements and/or dedications given therein. 

L. Preserve all the Invariant Sections of the Document, unaltered in their text 
and in their titles. Section numbers or the equivalent are not considered part 
of the section titles. 

M. Delete any section Entitled "Endorsements". Such a section may not be 
included in the Modified Version. 

N. Do not retitle any existing section to be Entitled "Endorsements" or to 
conflict in title with any Invariant Section. 

O. Preserve any Warranty Disclaimers. 

If the Modified Version includes new front-matter sections or appendices that 
qualify as Secondary Sections and contain no material copied from the Document, 
you may at your option designate some or all of these sections as invariant. To 
do this, add their titles to the list of Invariant Sections in the Modified 
Version's license notice. These titles must be distinct from any other section 
titles.

You may add a section Entitled "Endorsements", provided it contains nothing but 
endorsements of your Modified Version by various parties—for example, 
statements of peer review or that the text has been approved by an organization 
as the authoritative definition of a standard.

You may add a passage of up to five words as a Front-Cover Text, and a passage 
of up to 25 words as a Back-Cover Text, to the end of the list of Cover Texts 
in the Modified Version. Only one passage of Front-Cover Text and one of 
Back-Cover Text may be added by (or through arrangements made by) any one 
entity. If the Document already includes a cover text for the same cover, 
previously added by you or by arrangement made by the same entity you are 
acting on behalf of, you may not add another; but you may replace the old one, 
on explicit permission from the previous publisher that added the old one.

The author(s) and publisher(s) of the Document do not by this License give 
permission to use their names for publicity for or to assert or imply 
endorsement of any Modified Version.

=== 5. COMBINING DOCUMENTS
You may combine the Document with other documents released under this License, 
under the terms defined in section 4 above for modified versions, provided that 
you include in the combination all of the Invariant Sections of all of the 
original documents, unmodified, and list them all as Invariant Sections of your 
combined work in its license notice, and that you preserve all their Warranty 
Disclaimers.

The combined work need only contain one copy of this License, and multiple 
identical Invariant Sections may be replaced with a single copy. If there are 
multiple Invariant Sections with the same name but different contents, make the 
title of each such section unique by adding at the end of it, in parentheses, 
the name of the original author or publisher of that section if known, or else 
a unique number. Make the same adjustment to the section titles in the list of 
Invariant Sections in the license notice of the combined work.

In the combination, you must combine any sections Entitled "History" in the 
various original documents, forming one section Entitled "History"; likewise 
combine any sections Entitled "Acknowledgements", and any sections Entitled 
"Dedications". You must delete all sections Entitled "Endorsements".

=== 6. COLLECTIONS OF DOCUMENTS
You may make a collection consisting of the Document and other documents 
released under this License, and replace the individual copies of this License 
in the various documents with a single copy that is included in the collection, 
provided that you follow the rules of this License for verbatim copying of each 
of the documents in all other respects.

You may extract a single document from such a collection, and distribute it 
individually under this License, provided you insert a copy of this License 
into the extracted document, and follow this License in all other respects 
regarding verbatim copying of that document.

=== 7. AGGREGATION WITH INDEPENDENT WORKS
A compilation of the Document or its derivatives with other separate and 
independent documents or works, in or on a volume of a storage or distribution 
medium, is called an "aggregate" if the copyright resulting from the 
compilation is not used to limit the legal rights of the compilation's users 
beyond what the individual works permit. When the Document is included in an 
aggregate, this License does not apply to the other works in the aggregate 
which are not themselves derivative works of the Document.

If the Cover Text requirement of section 3 is applicable to these copies of the 
Document, then if the Document is less than one half of the entire aggregate, 
the Document's Cover Texts may be placed on covers that bracket the Document 
within the aggregate, or the electronic equivalent of covers if the Document is 
in electronic form. Otherwise they must appear on printed covers that bracket 
the whole aggregate.

=== 8. TRANSLATION
Translation is considered a kind of modification, so you may distribute 
translations of the Document under the terms of section 4. Replacing Invariant 
Sections with translations requires special permission from their copyright 
holders, but you may include translations of some or all Invariant Sections in 
addition to the original versions of these Invariant Sections. You may include 
a translation of this License, and all the license notices in the Document, and 
any Warranty Disclaimers, provided that you also include the original English 
version of this License and the original versions of those notices and 
disclaimers. In case of a disagreement between the translation and the original 
version of this License or a notice or disclaimer, the original version will 
prevail.

If a section in the Document is Entitled "Acknowledgements", "Dedications", or 
"History", the requirement (section 4) to Preserve its Title (section 1) will 
typically require changing the actual title.

=== 9. TERMINATION
You may not copy, modify, sublicense, or distribute the Document except as 
expressly provided under this License. Any attempt otherwise to copy, modify, 
sublicense, or distribute it is void, and will automatically terminate your 
rights under this License.

However, if you cease all violation of this License, then your license from a 
particular copyright holder is reinstated (a) provisionally, unless and until 
the copyright holder explicitly and finally terminates your license, and (b) 
permanently, if the copyright holder fails to notify you of the violation by 
some reasonable means prior to 60 days after the cessation.

Moreover, your license from a particular copyright holder is reinstated 
permanently if the copyright holder notifies you of the violation by some 
reasonable means, this is the first time you have received notice of violation 
of this License (for any work) from that copyright holder, and you cure the 
violation prior to 30 days after your receipt of the notice.

Termination of your rights under this section does not terminate the licenses 
of parties who have received copies or rights from you under this License. If 
your rights have been terminated and not permanently reinstated, receipt of a 
copy of some or all of the same material does not give you any rights to use it.

=== 10. FUTURE REVISIONS OF THIS LICENSE
The Free Software Foundation may publish new, revised versions of the GNU Free 
Documentation License from time to time. Such new versions will be similar in 
spirit to the present version, but may differ in detail to address new problems 
or concerns. See http://www.gnu.org/copyleft/.

Each version of the License is given a distinguishing version number. If the 
Document specifies that a particular numbered version of this License "or any 
later version" applies to it, you have the option of following the terms and 
conditions either of that specified version or of any later version that has 
been published (not as a draft) by the Free Software Foundation. If the 
Document does not specify a version number of this License, you may choose any 
version ever published (not as a draft) by the Free Software Foundation. If the 
Document specifies that a proxy can decide which future versions of this 
License can be used, that proxy's public statement of acceptance of a version 
permanently authorizes you to choose that version for the Document.

=== 11. RELICENSING
"Massive Multiauthor Collaboration Site" (or "MMC Site") means any World Wide 
Web server that publishes copyrightable works and also provides prominent 
facilities for anybody to edit those works. A public wiki that anybody can edit 
is an example of such a server. A "Massive Multiauthor Collaboration" (or 
"MMC") contained in the site means any set of copyrightable works thus 
published on the MMC site.

"CC-BY-SA" means the Creative Commons Attribution-Share Alike 3.0 license 
published by Creative Commons Corporation, a not-for-profit corporation with a 
principal place of business in San Francisco, California, as well as future 
copyleft versions of that license published by that same organization.

"Incorporate" means to publish or republish a Document, in whole or in part, as 
part of another Document.

An MMC is "eligible for relicensing" if it is licensed under this License, and 
if all works that were first published under this License somewhere other than 
this MMC, and subsequently incorporated in whole or in part into the MMC, (1) 
had no cover texts or invariant sections, and (2) were thus incorporated prior 
to November 1, 2008.

The operator of an MMC Site may republish an MMC contained in the site under 
CC-BY-SA on the same site at any time before August 1, 2009, provided the MMC 
is eligible for relicensing.

